Popover frontend component creation
droztech/droz-visu pull request #140
Opened 2024-03-21 18:19 UTC by Ftarganski

CU-86dt1rhry

## 📝 Description
- Popover frontend component creation

## 🚀 Why is this change required and behavior changes
Popover, activated with icon or text, with the possibility of placeholder, which has the possibility of internally rendering any type of structure.

## 💣 Is this a breaking change:
- [X] Yes
- [  ] No

- Creating a new component

## Checklist
- [X] I've created/modified some component
- [X] I've created/modified the component's stories
- [X] I've created/modified the component's tests

2024-03-21 21:29 UTC, YaGRRusso requested changes

2024-03-21 21:29 UTC, YaGRRusso commented on package/src/library/Popover/index.tsx
> +      <RadixPopover.Trigger asChild>
Acho que dá pra deixar o Popover um pouco mais atômico, assim temos mais liberdade para mudar o trigger e usar um botão ou até mesmo um texto se quisermos, acho que ficaria bom assim:

```
<Popover.Root>
  <Popover.Trigger>
    // assim não ficamos limitados a um trigger sendo só um ícone sempre
  </Popover.Trigger>
    <Popover.Content> // que ná verdade seria o Portal aqui, mas o nome Content é mais descritivo
    // aqui também temos liberdade para por qualquer coisa
  </Popover.Content>
</Popover.Root
```

Tem vários componentes que já são assim, um bem parecido que tu pode dar um olhada é o [FloatCard](https://visu.meudroz.com/?path=/story/floatcard-root--comum)

2024-03-21 21:29 UTC, YaGRRusso commented on package/src/library/Popover/index.tsx
> +      <RadixPopover.Trigger asChild>
Isso foi uma coisa que decidimos aquele dia no [Slack](https://coaktion.slack.com/archives/C05TSEMUD2N/p1710448677481589), por seguir um padrão mais [atômico](https://medium.com/rd-shipit/como-criar-componentes-react-com-uma-arquitetura-escal%C3%A1vel-usando-atomic-design-74a67aaf47e0)

2024-03-21 22:04 UTC, Ftarganski commented on package/src/library/Popover/index.tsx
> +      <RadixPopover.Trigger asChild>
Mas bah tchê.... buenas de boa esse indicação!

Tá feito!

2024-03-22 13:47 UTC, YaGRRusso requested changes

2024-03-22 13:47 UTC, YaGRRusso commented on docs/src/stories/Popover/Root.Stories.tsx
> +  component: Popover.Content,
Ta certo isso aqui? Temos um snippet pra criação de stories que é "storybookstory"

2024-03-22 13:47 UTC, YaGRRusso commented on package/src/library/Popover/Content.tsx
> +  className?: string
essas props já fazem parte da interface PopoverContentProps, como tu tá extendendo essa interface não precisaria ter reescrito isso aqui, a menos que tu queira desabilitar algum valor que tenha no extend

2024-03-22 13:47 UTC, YaGRRusso commented on package/src/library/Popover/Trigger.tsx
> +    <RadixPopover.Trigger asChild {...rest}>
Esse asChild tem que ser opcional, as vezes o usuário vai digitar só um texto no trigger e o asChild precisa obrigatoriamente que o children seja 1 tag (se não tiver tag dá erro e se tiver um fragment com mais de 1 tag também dá erro)

2024-03-22 13:57 UTC, Ftarganski commented on package/src/library/Popover/Trigger.tsx
> +    <RadixPopover.Trigger asChild {...rest}>
removido

2024-03-22 13:58 UTC, Ftarganski commented on package/src/library/Popover/Content.tsx
> +  className?: string
real! no content esqueci de remover

2024-03-22 14:14 UTC, YaGRRusso requested changes

2024-03-22 14:14 UTC, YaGRRusso commented on package/src/library/Popover/Content.tsx
> +        align={align}
se tu tá passando align={align} e side={side} e depois {...rest} no mesmo componentes, então tu não precisa passar manualmente esse align e side se tu não faz nenhum tratamento extra neles

2024-03-22 14:22 UTC, Ftarganski commented on package/src/library/Popover/Content.tsx
> +        align={align}
foi

2024-03-22 14:47 UTC, YaGRRusso approved these changes

2024-03-22 14:52 UTC, merged