Atualizar versão para 3.4.1
droztech/droz-visu pull request #155
Opened 2024-04-22 17:38 UTC by Ftarganski

**Description:**
DatePicker component creation.

**Code changes:**
- feat CU-86dtb1yy1

**Breaking change:**
- [X] Yes
- [] No

**Observation:**
Some additional information. (Optional)

2024-04-23 18:25 UTC, Ftarganski commented
Sim, está em Draft, mas se puderem já olhar eu agradeço. 

Faltam poucos ajustes.

2024-04-23 18:30 UTC, YaGRRusso commented on package/src/App.tsx
> +        />
O value do datepicker tem que ficar aqui também

2024-04-23 18:30 UTC, YaGRRusso commented on package/src/library/index.ts
>  export * from './types'
ordem alfabetica?

2024-04-23 18:31 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +}
O proprio Calendar não traz isso? Se ele não traz, deveria, tem que passar esses types pra lá se for o caso

2024-04-23 18:32 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +}
Esse eu tenho certeza que o Calendar exporta

2024-04-23 18:33 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +  >(null)
Isso não deve ficar no Datepicker, ele apenas vai receber o valor e exibir, a lógica precisa ser externa (externamente pode usar useMemo, react-hook-form etc)

2024-04-23 18:34 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +  }, [])
Pra que isso?

2024-04-23 18:35 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +    </div>
Usa o Popover

2024-04-23 18:36 UTC, YaGRRusso requested changes
Nem vou olhar o resto, quando passar a lógica do value pra fora e usar o Popover esse código vai ficar 1/3 do que é agora

2024-04-23 18:45 UTC, Ftarganski commented on package/src/library/index.ts
>  export * from './types'
só para arrumar mesmo..... huahuahua

2024-04-24 13:36 UTC, Ftarganski commented on package/src/library/DatePicker/index.tsx
> +  }, [])
usando estrutura mais básica, sem popover, estava controlando abertura e fechamento. Removi.

2024-04-24 13:36 UTC, Ftarganski commented on package/src/library/DatePicker/index.tsx
> +    </div>
Feito

2024-04-25 16:17 UTC, YaGRRusso requested changes

2024-04-25 18:03 UTC, Ftarganski commented on package/src/library/DatePicker/index.tsx
> +  value?: string
real, não precisa mesmo!

2024-04-25 18:23 UTC, Ftarganski commented on package/src/library/DatePicker/index.tsx
> +  value?: string
nope, mudamos para dentro

2024-04-25 18:23 UTC, Ftarganski commented on package/src/library/DatePicker/index.tsx
> +  }
booooa!

2024-04-25 18:26 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +      const endDate = formatDate(dates[dates.length - 1], undefined, language)
deixa os options como opcional nas props também, isso já funciona mesmo, é só liberar pro usuário, ou remove isso do helper se não vai ser usado, não tem pra que esperar uma prop que nunca será passada

2024-04-25 20:50 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +  const formatDates = (dates: Date[], language?: Intl.LocalesArgument) => {
Da onde que vem esse language? sjaksja

2024-04-25 20:51 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +}
```
type DatePickerProps = CalendarProps & {
  placeholder?: string
  icon?: InputIconProps['icon']
  options?: Intl.DateTimeFormatOptions
  language?: Intl.LocalesArgument,
}
```

2024-04-25 23:08 UTC, Ftarganski commented on package/src/library/DatePicker/index.tsx
> +}
caraca, passei options e esqueci o idioma...

2024-04-26 14:06 UTC, YaGRRusso commented on package/src/library/DatePicker/index.tsx
> +  const formatDates = (dates: Date[], language?: Intl.LocalesArgument) => {
Não precisa passar o languages aqui, isso vai vir da propria prop do componente, testa, coloca isso no app e tenta colocar no App e ve se vai funcionar assim da forma que tá. provalvemente não vai

2024-04-26 16:43 UTC, YaGRRusso approved these changes

2024-04-26 16:44 UTC, merged